GET https://63c55501f3a73b347853986b.mockapi.io/users?page=1&limit=10

###

GET https://63c55501f3a73b347853986b.mockapi.io/users


###

POST https://63c55501f3a73b347853986b.mockapi.io/users
Content-Type: application/json

  {
    "name": "camera",
    "image": "/images/avatar/avatar1.jpeg",
    "description": "by Fulcrum",
    "price": 30000
  }